manual QA notes for interims
comicrelief/engineering-handbook pull request #11
Opened 2019-06-17 14:25 UTC by KrupaPammi

2019-06-18 08:52 UTC, pvhee commented on qa/manualQA.md
> +To ensure that the application meets the business and user requirements
maybe use bullet points too, as done below?

2019-06-18 08:52 UTC, pvhee commented on qa/manualQA.md
> +XS – Mobile Portrait View
needs indenting

2019-06-18 08:52 UTC, pvhee requested changes
Looks good, apart from some cosmetic changes needed

2019-06-18 09:02 UTC, KrupaPammi commented on qa/manualQA.md
> +To ensure that the application meets the business and user requirements
added

2019-06-18 09:02 UTC, KrupaPammi commented on qa/manualQA.md
> +XS – Mobile Portrait View
fixed

2019-06-24 14:24 UTC, pvhee approved these changes

2019-06-24 14:26 UTC, merged